// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fuiofiwsgtwnzrwwdalq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ1aW9maXdzZ3R3bnpyd3dkYWxxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0ODgxMDMsImV4cCI6MjA3NDA2NDEwM30.eiSHSpxxrsQK-sCRNHz4rjBCir_a9BDzjJgZ22lfssU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});